version: 2
updates:
  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/ticketing-core-service"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "JuanLuisGozaloFdez"

  - package-ecosystem: "npm"
    directory: "/wallet-assets-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/checkin-validation-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/users-identity-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/payments-orders-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/notifications-comms-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/admin-event-ops-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/nft-marketplace-integration"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/api-gateway-bff"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/mobile-app-fans"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/admin-web-portal"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/checkin-scanner-app"
    schedule:
      interval: "weekly"

  # Docker images
  - package-ecosystem: "docker"
    directory: "/platform-infra"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
